apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressName }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ {{ .Values.ingressName }}.{{ .Values.namespace }}.com ]
      secretName: tls-{{ .Values.ingressName }}-{{ .Values.namespace }}
  rules:
    - host: {{ .Values.ingressName }}.{{ .Values.namespace }}.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wasmfrp
                port: { number: 80 }
